In [1]:
import h2o
from h2o.automl import H2OAutoML

ModuleNotFoundError: ignored

In [ ]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
  Starting server from C:\Users\Ryan\anaconda3\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\Ryan\AppData\Local\Temp\tmpn02mms16
  JVM stdout: C:\Users\Ryan\AppData\Local\Temp\tmpn02mms16\h2o_Ryan_started_from_python.out
  JVM stderr: C:\Users\Ryan\AppData\Local\Temp\tmpn02mms16\h2o_Ryan_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  --------------------------------
H2O_cluster_uptime:         05 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.1.3
H2O_cluster_version_age:    21 days, 23 hours and 47 minutes
H2O_cluster_name:           H2O_from_python_Ryan_czwyu1
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    5.302 Gb
H2O_cluster_total_cores:    12
H2O_cluster_allowed_cores:  12
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.12 final
--------------------------  --------------------------------

In [ ]:
data = h2o.import_file('train_.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
features=data.columns

In [ ]:
features

['Month', 'Avg_sunspot_count']

In [ ]:
output='Avg_sunspot_count'

In [ ]:
aml= H2OAutoML(max_models=7, max_runtime_secs=600, seed=2)

In [ ]:
aml.train(x = features, y = output, training_frame = data)

AutoML progress: |
17:20:48.657: AutoML: XGBoost is not available; skipping it.

███████████████████████████████████████████████████████████████| (done) 100%
Model Details
=============
H2OStackedEnsembleEstimator :  Stacked Ensemble
Model Key:  StackedEnsemble_AllModels_1_AutoML_1_20220730_172048

No model summary for this model

ModelMetricsRegressionGLM: stackedensemble
** Reported on train data. **

MSE: 374.4166429058741
RMSE: 19.349848653306672
MAE: 13.653411455550907
RMSLE: 0.5024328197077986
R^2: 0.9200316015665855
Mean Residual Deviance: 374.4166429058741
Null degrees of freedom: 3143
Residual degrees of freedom: 3139
Null deviance: 14720388.908078894
Residual deviance: 1177165.9252960682
AIC: 27563.64624845324

ModelMetricsRegressionGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 533.3970904295339
RMSE: 23.095391107957752
MAE: 16.396379701142376
RMSLE: 0.547991853579071
R^2: 0.8860763487444222
Mean Residual Deviance: 533.3970904295339
Null degrees of freedom: 3143
Residual degrees of freedom: 3140
Null deviance: 14738159.709531993
Residual deviance: 1677000.4523104548
AIC: 28674.298294305474

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,1.641918e+01,0.359946,1.593400e+01,1.672936e+01,1.622144e+01,1.640797e+01,1.680312e+01
1,mean_residual_deviance,5.335978e+02,50.226510,4.837761e+02,5.449622e+02,5.048155e+02,5.203646e+02,6.140709e+02
2,mse,5.335978e+02,50.226510,4.837761e+02,5.449622e+02,5.048155e+02,5.203646e+02,6.140709e+02
3,null_deviance,2.947632e+06,316694.470000,2.569388e+06,3.396800e+06,3.061405e+06,2.740479e+06,2.970088e+06
4,r2,8.852781e-01,0.010464,8.795199e-01,8.959646e-01,8.966097e-01,8.810226e-01,8.732737e-01
5,residual_deviance,3.352587e+05,28127.969000,3.067141e+05,3.515006e+05,3.165193e+05,3.257482e+05,3.758114e+05
6,rmse,2.307988e+01,1.070677,2.199491e+01,2.334443e+01,2.246810e+01,2.281150e+01,2.478045e+01
7,rmsle,5.527311e-01,0.019796,5.197297e-01,5.677240e-01,5.661477e-01,5.494099e-01,5.606442e-01

In [ ]:
lb=aml.leaderboard
lb.head()

model_id,rmse,mse,mae,rmsle,mean_residual_deviance
StackedEnsemble_AllModels_1_AutoML_1_20220730_172048,23.0954,533.397,16.3964,0.547992,533.397
StackedEnsemble_BestOfFamily_1_AutoML_1_20220730_172048,23.1895,537.755,16.4921,0.555162,537.755
GBM_3_AutoML_1_20220730_172048,23.2048,538.464,16.5585,0.570138,538.464
GBM_4_AutoML_1_20220730_172048,23.2485,540.494,16.5333,0.541082,540.494
GBM_2_AutoML_1_20220730_172048,23.395,547.327,16.7296,0.586545,547.327
GBM_1_AutoML_1_20220730_172048,30.6812,941.334,22.2255,0.772806,941.334
XRT_1_AutoML_1_20220730_172048,67.6094,4571.03,55.074,1.33912,4571.03
GLM_1_AutoML_1_20220730_172048,68.4244,4681.9,55.7151,1.34804,4681.9
DRF_1_AutoML_1_20220730_172048,68.4267,4682.21,55.7168,1.34806,4682.21

In [ ]:
data2= h2o.import_file('test_.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
preds = aml.build_models

In [ ]:
pred=aml.leader.predict(data2)

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

In [ ]:
print(pred)

predict
24.6896
24.6896
24.6896
24.6896
24.6896
24.6896
24.6896
24.6896
24.6896
24.6896

In [ ]:
d = pred.as_data_frame()

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('test_.csv')

df.head()

        Month
0  01-01-2011
1  02-01-2011
2  03-01-2011
3  04-01-2011
4  05-01-2011

In [ ]:
t=df.copy()

In [ ]:
d

       predict
0    24.689562
1    24.689562
2    24.689562
3    24.689562
4    24.689562
..         ...
115  24.689562
116  24.689562
117  24.689562
118  24.689562
119  24.689562

[120 rows x 1 columns]

In [ ]:
t

          Month
0    01-01-2011
1    02-01-2011
2    03-01-2011
3    04-01-2011
4    05-01-2011
..          ...
115  08-01-2020
116  09-01-2020
117  10-01-2020
118  11-01-2020
119  12-01-2020

[120 rows x 1 columns]

In [ ]:
res=pd.concat([t,d], axis=1)

In [ ]:
res

          Month    predict
0    01-01-2011  24.689562
1    02-01-2011  24.689562
2    03-01-2011  24.689562
3    04-01-2011  24.689562
4    05-01-2011  24.689562
..          ...        ...
115  08-01-2020  24.689562
116  09-01-2020  24.689562
117  10-01-2020  24.689562
118  11-01-2020  24.689562
119  12-01-2020  24.689562

[120 rows x 2 columns]

In [ ]:
 res = res.rename({'predict':'Avg_sunspot_count'}, axis=1)

In [ ]:
res

          Month  Avg_sunspot_count
0    01-01-2011          24.689562
1    02-01-2011          24.689562
2    03-01-2011          24.689562
3    04-01-2011          24.689562
4    05-01-2011          24.689562
..          ...                ...
115  08-01-2020          24.689562
116  09-01-2020          24.689562
117  10-01-2020          24.689562
118  11-01-2020          24.689562
119  12-01-2020          24.689562

[120 rows x 2 columns]

In [ ]:
res

          Month  Avg_sunspot_count
0    01-01-2011          24.689562
1    02-01-2011          24.689562
2    03-01-2011          24.689562
3    04-01-2011          24.689562
4    05-01-2011          24.689562
..          ...                ...
115  08-01-2020          24.689562
116  09-01-2020          24.689562
117  10-01-2020          24.689562
118  11-01-2020          24.689562
119  12-01-2020          24.689562

[120 rows x 2 columns]

In [ ]:
res.to_csv('Subission_AT_22.csv',index=False)